FROM apache/airflow:2.10.5

USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y gcc g++ libkrb5-dev && \
    apt-get clean

USER airflow

# Install Python packages
RUN pip install --no-cache-dir \
    minio==7.1.15 \
    delta-spark==3.0.0 \
    pyspark==3.5.0 \
    deltalake==0.15.1 \
    pyarrow==14.0.1 \
    fsspec==2023.12.0 \
    s3fs==2023.12.0